### ISSUE TITLE
Entry points and SSR

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#33]
Not sure if this belong here or under SSR, but it's really just a question/clarification. From what I can tell, it looks like this sample has the same entry point(s) for client and server (./routes and ./client/routes respectively).

So where normally I would have a server only entry point to not have `Loading...` or whatever display on the initial page load, how does SSR handle this when it looks like both entry point are the same? Does it try server and if not, fallback to client or are all routes server and if so why the client entry point? Hopefully I am making at least a little bit of sense...

**Comment by eXon** [comment]
Hey,

The entry point for the server is in entry/server/entry.js and client on entry/client/entry.js.

For the routes, they are exactly the same. You can do your loading exactly the same way you're probably used to with the ReactMeteorData mixin:

```javascript
var TodoListLoader = React.createClass({
  mixins: [ReactMeteorData],
  getMeteorData() {
    // This is the place to subscribe to any data you need
    var handle = Meteor.subscribe("todoList", this.props.id);

    return {
      todoListLoading: ! handle.ready(), // Use handle to show loading state
      todoList: TodoLists.findOne(this.props.id),
      todoListTasks: Tasks.find({listId: this.props.id}).fetch()
    };
  },
  render() {
    // Show a loading indicator if data is not ready
    if (this.data.todoListLoading) {
      return <LoadingSpinner />;
    }

    // Render a component and pass down the loaded data
    return (
      <TodoList
        list={this.data.todoList}
        tasks={this.data.todoListTasks} />
    );
  }
});
```

When run on the server, your handle.ready() will always return true. On the client, it will display the loading until you have the data.

There is no React code for server and React code for the client. They both share the same (at least in production when you have SSR. You don't have SSR in development because it would make the Meteor server restart and break hot reloading).

Is it more clear?

**Comment by genyded** [comment]
OK - got it - I think - bring meteor into the mix is a bit different than pure React, My largest concern is having the initial page load ASAP (aka pre-fetching).

**Comment by eXon** [comment]
With Meteor subscription and meteorhacks:fast-render, it takes care of rehydratation for you :)
